- name: Config LC_ALL for OS
  lineinfile:
    path: /etc/profile
    regexp: '^export LC_ALL'
    line: "export LC_ALL={{ LC_ALL }}"

- name: set /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: 'HISTTIMEFORMAT',line: 'export HISTTIMEFORMAT="%F %T `whoami` "' }
    - { regexp: '^HISTSIZE',line: 'HISTSIZE=3000' }
    - { regexp: '^shopt',line: 'shopt -s histappend' }
  notify: source /etc/profile

- name: config /etc/rc.d/rc.local is Huge pages
  template:
    src: rc.local
    dest: /etc/rc.d/rc.local
    owner: root
    group: root
    mode: '0755'
