- name: set /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: 'GSSAPIAuthentication',line: 'GSSAPIAuthentication no' }
    - { regexp: 'UseDNS',line: 'UseDNS no' }
  notify: restart sshd

- name: stop postfix
  service:
    name: postfix
    state: stopped
    enabled: no

- name: dmidecode -s system-product-name
  shell: dmidecode -s system-product-name
  ignore_errors: yes
  register: system_model

- name: stop NetworkManager
  service:
    name: NetworkManager
    state: stopped
    enabled: no
  when: system_model.stdout != "OpenStack Compute"
