- name: Add CentOS-Base repository
  template:
    src: repo/CentOS-Base.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
    owner: root
    group: root
  when: "(install_yum_mode) == 'aliyun'"

- name: Add epel repository
  template:
    src: repo/epel.repo
    dest: /etc/yum.repos.d/epel.repo
    owner: root
    group: root
  when: "(install_yum_mode) == 'aliyun'"
