- name: Set /etc/security/limits.conf
  pam_limits:
    domain: '*'
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: '65535'
  with_items:
    - { type: 'soft',item: 'nproc' }
    - { type: 'hard',item: 'nproc' }
    - { type: 'soft',item: 'nofile' }
    - { type: 'hard',item: 'nofile' }

- name: Set /etc/sysctl.conf
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: 'vm.swappiness',value: '0' }
    - { name: 'kernel.sysrq',value: '0' }
    - { name: 'kernel.msgmnb',value: '65536' }
    - { name: 'kernel.msgmax',value: '65536' }
    - { name: 'kernel.shmmax',value: '8589934592' }
    - { name: 'kernel.shmall',value: '8589934592' }
    - { name: 'kernel.pid_max',value: '65536' }
    - { name: 'kernel.core_uses_pid',value: '1' }
    - { name: 'net.core.rmem_default',value: '8388608' }
    - { name: 'net.core.rmem_max',value: '16777216' }
    - { name: 'net.core.wmem_default',value: '8388608' }
    - { name: 'net.core.wmem_max',value: '16777216' }
    - { name: 'net.ipv4.tcp_rmem',value: '4096 131072 6291456' }
    - { name: 'net.ipv4.tcp_wmem',value: '4096 131072 6291456' }
    - { name: 'net.ipv4.tcp_mem',value: '134217728 1073741824 2147483648' }
    - { name: 'net.core.netdev_max_backlog',value: '262144' }
    - { name: 'net.ipv4.tcp_max_syn_backlog',value: '8192' }
    - { name: 'net.ipv4.tcp_congestion_control',value: 'htcp' }
    - { name: 'net.ipv4.tcp_mtu_probing',value: '1' }
    - { name: 'net.ipv4.ip_local_port_range',value: '10240 65000' }
    - { name: 'net.ipv4.tcp_tw_recycle',value: '1' }
    - { name: 'net.ipv4.tcp_tw_reuse',value: '1' }
    - { name: 'net.ipv4.conf.all.rp_filter',value: '1' }
    - { name: 'net.ipv4.conf.default.rp_filter',value: '1' }
    - { name: 'net.ipv4.conf.default.accept_source_route',value: '0' }
    - { name: 'net.ipv4.tcp_syncookies',value: '1' }
    - { name: 'net.ipv4.tcp_fin_timeout',value: '30' }
    - { name: 'net.core.somaxconn',value: '65535' }
    - { name: 'net.ipv4.tcp_max_orphans',value: '3276800' }
    - { name: 'net.unix.max_dgram_qlen',value: '20480' }
    - { name: 'fs.file-max',value: '1024000' }
    - { name: 'fs.inotify.max_user_watches',value: '1024000' }
    - { name: 'fs.inotify.max_user_instances',value: '512' }
    - { name: 'net.ipv4.tcp_retries2',value: '5' }
    - { name: 'net.ipv4.tcp_synack_retries',value: '3' }
    - { name: 'net.ipv4.tcp_syn_retries',value: '3' }
    - { name: 'net.ipv4.tcp_window_scaling',value: '1' }
    - { name: 'net.ipv4.tcp_timestamps',value: '1' }
    - { name: 'net.ipv4.tcp_no_metrics_save',value: '1' }
    - { name: 'net.ipv4.tcp_keepalive_time',value: '60' }
    - { name: 'net.ipv4.tcp_keepalive_intvl',value: '30' }
    - { name: 'net.ipv4.tcp_keepalive_probes',value: '5' }
    - { name: 'net.ipv4.neigh.default.gc_thresh1',value: '1024' }
    - { name: 'net.ipv4.neigh.default.gc_thresh2',value: '2048' }
    - { name: 'net.ipv4.neigh.default.gc_thresh3',value: '4096' }
  notify: route flush
