- name: set /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: 'GSSAPIAuthentication',line: 'GSSAPIAuthentication no' }
    - { regexp: 'UseDNS',line: 'UseDNS no' }
  notify: restart sshd

- name: stop postfix
  service:
    name: postfix
    state: stopped
    enabled: no
