- name: set the date and time via NTP
  shell: ntpdate {{ntp_server}}
  ignore_errors: yes

- name: set the hardware clock from the current system time
  shell: hwclock -w 
  ignore_errors: yes

- name: config /etc/chrony.conf
  template:
    src: chrony.conf
    dest: /etc/chrony.conf
  notify: restart chronyd
