- name: install bash package
  yum:
    name:
      - wget
      - vim 
      - net-tools
      - bash-completion
      - bash-completion-extras
      - lrzsz
      - sshpass
      - gcc
      - gcc-c++
      - libffi-devel
      - openssl-devel
      - python-devel
      - ntpdate
      - chrony 
    state: present

- name: Disable SELinux
  selinux:
    state: disabled
  
- name: systemctl stop firewalld.service
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai

- name: Config LC_ALL for OS
  lineinfile:
    path: /etc/profile
    regexp: '^export LC_ALL'
    line: "export LC_ALL={{ LC_ALL }}"

- name: config /etc/systemd/system.conf
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^DefaultLimitNOFILE',line: 'DefaultLimitNOFILE=65535' }
    - { regexp: '^DefaultLimitNPROC',line: 'DefaultLimitNPROC=65535' }
  notify: systemctl daemon-reexec

